server:
  port: 31000
#  servlet:
#      context-path: /server

#variable:
#  profiles : dev

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/server?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 'customer88'

#  解决 Failed to start bean ‘documentationPluginsBootstrapper’; nested exception is java.lang.NullPointerException
  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher


#swagger
knife4j:
  #开启增强配置
  enable: true
  #开启生产环境屏蔽
  production: false
  basic:
    enable: false
    username: admin
    password: 123456