server:
  port: 7002
  
spring:
  application:
    name: cv-demo
  cloud:
    nacos:
      config:
        server-addr: @config.server-addr@
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
  config:
    import:
      - optional:nacos:brightcomplete.yaml
      - optional:nacos:brightcomplete-@profile.name@.yaml